package ch.thp.mas.llm.variance.metanalysis;

public enum MetaAnalysisKind {
    SUMMARY,
    WORD_DRIFT,
    BASELINE_SCATTER,
    CREATIVE_CONTROL_QUANTILES,
    ROUNDTRIP_LANGUAGE_DESTINATION,
    ROUNDTRIP_STATION_MODEL_COUNTS,
    ROUNDTRIP_ROUTE_MODEL_COUNTS,
    ROUNDTRIP_MIDDLE_POSITION_SUMMARY,
    DE_BASELINE_ARCHETYPE_VARIANCE,
    FIRST_RESPONSE_EFFECT,
    MANUAL_EVALUATION_SAMPLE,
    MANUAL_CREATIVE_EVALUATION_SUMMARY
}
