package ch.thp.mas.llm.variance.analyze;

public enum PromptEvaluation {
    ADVISORY_RECOMMENDATION_SWISS_ROUND_TRIP,
    FACTUAL_CRITICAL_BERN_ZURICH_CONNECTION,
    LITERAL_FORMAT_CRITICAL_TRAVELER_GUIDANCE,
    CREATIVE_GENERATIVE_LUCERNE_MARKETING
}
